def dashboard_kpis(df):
    total_students = len(df)
    average_sgpi = round(df['SGPI'].mean(), 2)
    average_attendance = round(df['Attendance'].mean(), 2)
    highest_sgpi = df['SGPI'].max()
    lowest_sgpi = df['SGPI'].min()
    at_risk = len(df[(df['Attendance'] < 75) | (df['SGPI'] < 6)])

    print("\n========== DASHBOARD KPI ==========")
    print(f"Total Students: {total_students}")
    print(f"Average SGPI: {average_sgpi}")
    print(f"Average Attendance: {average_attendance}%")
    print(f"Highest SGPI: {highest_sgpi}")
    print(f"Lowest SGPI: {lowest_sgpi}")
    print(f"At Risk Students: {at_risk}")